### ISSUE TITLE
XML parsing broken on some files

### ISSUE THREAD

**Issue by jenda122** [Matfyz-Developer-Student-Club/matfyz-activity-sport-tracker#22]
Hi,
processor.py cannot parse the following file generated by gpsbabel:

```
<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.0" creator="GPSBabel - https://www.gpsbabel.org" xmlns="http://www.topografix.com/GPX/1/0">
  <time>2020-11-12T09:05:30.276Z</time>
  <bounds minlat="50.053291000" minlon="14.430131000" maxlat="50.103435000" maxlon="14.448442000"/>
  <trk>
    <name>2020-11-12T08:38:40Z</name>
    <trkseg>
      <trkpt lat="50.054873000" lon="14.442409000">
        <ele>261.870</ele>
        <time>2020-11-12T08:38:41Z</time>
      </trkpt>
    </trkseg>
  </trk>
</gpx>
```
```
--- Logging error ---
Traceback (most recent call last):
  File "../gpx.py", line 43, in process_input_data
    activities = (root.find(trk[0])).find(namespace + self.__TRKSEG_ELM).findall(
AttributeError: 'NoneType' object has no attribute 'findall'
```

It works when I remove the bounds tag. Stepping through the code:
```
In [17]: tree = ET.parse("./aa.gpx")
In [18]: root = tree.getroot()
In [19]: root
Out[19]: <Element '{http://www.topografix.com/GPX/1/0}gpx' at 0x7f34e561f4a0>
In [20]: trk = findall('\{.*\}.*', root[1].tag if len(root) > 1 else root[0].tag)
In [21]: namespace = trk[0][:-3]
In [22]: namespace
Out[22]: '{http://www.topografix.com/GPX/1/0}bou'
```
which looks bad. I'm no expert at XML parsing, so I'm not sure how this should work, I can have further look in the evening.

**Comment by MichalKyjovsky** [comment]
Hi, thank you for the report!! It is really appreciated it. I will investigate it as soon as possible. Generally, each of the sports tracking application using GPX has slight differences in the header. Since we were aiming more or less on STRAVA application or application producing similar format based on provided test data, not all of the edge cases are covered yet.

**Comment by MatejLieskovsky** [comment]
Can you please list at least one *offline* tracker that generates valid data? Output of GPS Logger on Android seems to always cause a 500 Error, output from https://labs.easyblog.it/maps/gpx-simplify-optimizer/ passed once but I'm having no luck uploading any further files, and I really don't want to get Strava just for this one competition.

**Comment by MichalKyjovsky** [comment]
Hello @MatejLieskovsky,

we do really appreciate your feedback, unfortunately, the STRAVA was chosen by organizers as a tracking tool. Our application as for now supports this specific format, please understand, that we are not able to support all derivatives of GPX, since there are so many of them. If you insist to avoid using the STRAVA, I do recommend for instance __mapy.cz__ to track your progress afterward, or could you please provide some sample of the failing input data, which you had used, and we will check out what is our possibilities. 

Kind regards and stay tuned!

Michal Kyjovsky.

**Comment by MichalKyjovsky** [comment]
Hello @jh-cg ,

I was finally able to reach out to the problem you spotted. It should be fixed now, so I assume that if my colleagues do not find any concerns about the upcoming pull request, I will upload it to the server.

I am just wondering why do you want to track a single GPX point?

Kind regards,
Michal Kyjovsky.

**Comment by jenda122** [comment]
Hi,
it was a minimal testcase. Of course I am uploading the entire track. (and why it's from gpsbabel: I have Garmin Edge 705, which uses https://en.wikipedia.org/wiki/Training_Center_XML, and I'm using gpsbabel to convert it to GPX)

**Comment by MichalKyjovsky** [comment]
Thank you for your rapid response. Current implementation should work regardless of the producer of the GPX (hopefully), as I mentioned above, there are a vast amount of derivatives.

Anyway, thank you for your insights and time and we are looking forward to hearing from you soon.

Kind regards,
Michal Kyjovsky.
