### ISSUE TITLE
Show user's own total distances

### ISSUE THREAD

**Issue by regnarg** [Matfyz-Developer-Student-Club/matfyz-activity-sport-tracker#35]
Because both credit awarding and competition results are based on total sums of user's distances, it is weird that the user cannot see their own results. It would be useful to see one's own:

* total distance on foot, on bike
* number of points for credit calculated based on the rules
* for each competition, one's own result (i.e. the number shown in the leaderboard but even if the user is not among the first ten, so that they know how much they need to catch up)

Is this planned? Would you accept PR for this?

**Comment by peterkorcsok** [comment]
Hi Filip,
thank you for your comment.

- Displaying of user's result in competitions is currently in development - we will be displaying all users in competition instead of just the top ten. The estimated time of release is today or tomorrow.
- Shortly after complete results (or maybe together with them) we will also display the total distances on foot/on bike on the respective competition page.
- The total points for the credit are definitely planned (at least for the Department of Physical Education) and so we can display this information also for users. Since there are some other tasks with higher priorities (e.g. our other school and work projects 😄), I cannot estimate the time of release. Still, I hope it would be during the first week in December.

If you would like to take part in some development, we will welcome any PR or you can join our team 😄
